export const AUTH_REQUEST_COMECO = 'AUTH_REQUEST_COMECO';
export const AUTH_REQUEST_SUCESSO = 'AUTH_REQUEST_SUCESSO';
export const AUTH_REQUEST_ERRO = 'AUTH_REQUEST_ERRO';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const LEITURA_REQUEST_COMECO = 'LEITURA_REQUEST_COMECO';
export const LEITURA_REQUEST_SUCESSO = 'LEITURA_REQUEST_SUCESSO';
export const LEITURA_REQUEST_ERRO = 'LEITURA_REQUEST_ERRO';
export const LEITURA_CLEAR_EVERYTHING = 'LEITURA_CLEAR_EVERYTHING';

export const STORE_CLEAR_ERROR = 'STORE_CLEAR_ERROR';
