export const AUTH_REQUEST_COMECO = 'AUTH_REQUEST_COMECO';
export const AUTH_REQUEST_SUCESSO = 'AUTH_REQUEST_SUCESSO';
export const AUTH_REQUEST_ERRO = 'AUTH_REQUEST_ERRO';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
